FROM centos:8

RUN  yum -y update  && yum -y upgrade &&\ 
yum -y install make  gcc gcc-c++ git wget libcurl-devel zlib-devel bzip2  bzip2-devel xz-devel

WORKDIR /home/

RUN git clone https://github.com/ebiggers/libdeflate

WORKDIR /home/libdeflate

RUN make

RUN make install
	
WORKDIR /home/
	
RUN mkdir -p /home/vcfshark 
	
WORKDIR /home/vcfshark

RUN git clone https://github.com/refresh-bio/VCFShark.git  

WORKDIR /home/vcfshark/VCFShark

RUN ./install.sh

RUN make

ENV LD_LIBRARY_PATH  /usr/local/lib
