FROM ubuntu:18.04

RUN apt-get update && apt-get upgrade --yes && \
    apt-get --yes install build-essential git cmake wget libcurl4-gnutls-dev zlibc zlib1g zlib1g-dev libbz2-dev liblzma-dev
	
WORKDIR /home/

RUN git clone https://github.com/ebiggers/libdeflate

WORKDIR /home/libdeflate

RUN make

RUN make install
	
WORKDIR /home/

RUN mkdir -p /home/vcfshark 
	
WORKDIR /home/vcfshark

RUN git clone https://github.com/refresh-bio/VCFShark.git

WORKDIR /home/vcfshark/VCFShark

RUN ./install.sh

RUN make

ENV LD_LIBRARY_PATH  /usr/local/lib
